export interface Resource {
  id: string;
  titleEn: string;
  titleBn: string;
  descriptionEn: string;
  descriptionBn: string;
  contentEn: string;
  contentBn: string;
  category: string;
  type: 'article' | 'video' | 'infographic';
  targetAudience: string;
}

export const resources: Resource[] = [
  {
    id: 'mango_peel_composting',
    titleEn: 'How to Compost Mango Peels',
    titleBn: 'আম পিল করে সার তৈরি করুন',
    descriptionEn: 'Learn the simple 3-step process to compost mango peels into nutrient-rich soil.',
    descriptionBn: 'আম পিল দিয়ে পুষ্টিকর মাটি তৈরি করার 3-ধাপ প্রক্রিয়া শিখুন।',
    contentEn: 'Mango peels are rich in nutrients and fiber. Layer them with dry leaves and cow dung in a pit. Within 3-4 months, you will have rich compost ready for your garden.',
    contentBn: 'আম পিল পুষ্টি এবং তন্তু সমৃদ্ধ। এটি শুষ্ক পাতা এবং গোবরের সাথে একটি গর্তে স্তর করুন। 3-4 মাসের মধ্যে আপনার বাগানের জন্য সমৃদ্ধ সার প্রস্তুত হবে।',
    category: 'composting',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'banana_peel_composting',
    titleEn: 'Banana Peel Composting Guide',
    titleBn: 'কলার খোসা সার তৈরির গাইড',
    descriptionEn: 'Turn banana peels into nutrient-rich compost with this easy method.',
    descriptionBn: 'সহজ পদ্ধতিতে কলার খোসা পুষ্টিকর সার তে রূপান্তরিত করুন।',
    contentEn: 'Banana peels are excellent for composting. Cut them into small pieces and layer with garden soil. They decompose quickly and add potassium to your soil.',
    contentBn: 'কলার খোসা সার তৈরির জন্য চমৎকার। ছোট টুকরা করে মাটির সাথে স্তর করুন। এগুলি দ্রুত বিয়োজিত হয় এবং মাটিতে পটাসিয়াম যোগ করে।',
    category: 'composting',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'seasonal_storage',
    titleEn: 'Seasonal Vegetable Storage Techniques',
    titleBn: 'ঋতুভিত্তিক সবজি সংরক্ষণ কৌশল',
    descriptionEn: 'Learn how to store seasonal vegetables to extend their shelf life.',
    descriptionBn: 'ঋতুভিত্তিক সবজি সংরক্ষণ করে তাদের শেলফ লাইফ বাড়ান।',
    contentEn: 'Different vegetables require different storage conditions. Leafy greens need moisture, root vegetables need darkness, and tomatoes need room temperature.',
    contentBn: 'বিভিন্ন সবজির আলাদা আলাদা সংরক্ষণ শর্ত প্রয়োজন। পাতা যুক্ত সবজিতে আর্দ্রতা, মূল সবজিতে অন্ধকার, এবং টমেটো ঘরের তাপমাত্রা প্রয়োজন।',
    category: 'storage',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'budget_recipes',
    titleEn: '10 Budget-Friendly Nutritious Recipes',
    titleBn: '10 সাশ্রয়ী পুষ্টিকর রেসিপি',
    descriptionEn: 'Delicious recipes using affordable ingredients available in Bangladesh.',
    descriptionBn: 'বাংলাদেশে সহজলভ্য সাশ্রয়ী উপাদান ব্যবহার করে সুস্বাদু রেসিপি।',
    contentEn: 'Rice and lentils are affordable staples. Combine with seasonal vegetables like squash, eggplant, and spinach for nutritious meals.',
    contentBn: 'চাউল এবং ডাল সাশ্রয়ী প্রধান খাবার। কুমড়া, বেগুন এবং পালং শাকের মতো মৌসুমী সবজির সাথে মিশিয়ে পুষ্টিকর খাবার তৈরি করুন।',
    category: 'meal-planning',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'food_waste_reduction',
    titleEn: 'Food Waste Reduction Strategies',
    titleBn: 'খাদ্য বর্জ্য হ্রাস কৌশল',
    descriptionEn: 'Practical methods to reduce food waste and save money.',
    descriptionBn: 'খাদ্য বর্জ্য হ্রাস করে অর্থ সাশ্রয�� করুন।',
    contentEn: 'Plan meals, store properly, and use vegetable scraps for stock. About 30% of food is wasted globally; reduce this at home.',
    contentBn: 'খাবার পরিক��্পনা করুন, সঠিকভাবে সংরক্ষণ করুন এবং সবজির অবশেষ স্টক তৈরিতে ব্যবহার করুন।',
    category: 'waste-reduction',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'traditional_preservation',
    titleEn: 'Traditional Bengali Food Preservation Methods',
    titleBn: 'ঐতিহ্যবাহী বাঙালি খাদ্য সংরক্ষণ পদ্ধতি',
    descriptionEn: 'Learn ancestral techniques for preserving food without refrigeration.',
    descriptionBn: 'রেফ্রিজারেশন ছাড়াই খাদ্য সংরক্ষণের ঐতিহ্যবাহী কৌশল শিখুন।',
    contentEn: 'Fermentation, salting, and pickling are traditional methods. Used for centuries in Bengal to preserve vegetables and fish.',
    contentBn: 'গাঁজন, লবণ এবং আচার ঐতিহ্যবাহী পদ্ধতি। শতাব্দী ধরে বাংলায় সবজি এবং মাছ সংরক্ষণে ব্যবহৃত হয়েছে।',
    category: 'storage',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'iot_for_farmers',
    titleEn: 'IoT Sensors for Farmers: Watering Guide',
    titleBn: 'কৃষকদের জন্য IoT সেন্সর: সেচ গাইড',
    descriptionEn: 'How to use IoT sensors to optimize watering schedules and increase yield.',
    descriptionBn: 'IoT সেন্সর ব্যবহার করে সেচ সময়সূচী অনুকূল করুন এবং ফসল বৃদ্ধি করুন।',
    contentEn: 'Soil moisture sensors can save 30% water while increasing crop yield. Install simple sensors to monitor soil conditions.',
    contentBn: '30% জল সাশ্রয় করে ফসল বৃদ্ধি করতে মাটির আর্দ্রতা সেন্সর ব্যবহার করুন।',
    category: 'waste-reduction',
    type: 'article',
    targetAudience: 'farmer',
  },
  {
    id: 'meal_planning_guide',
    titleEn: 'Weekly Meal Planning for Budget Control',
    titleBn: 'বাজেট নিয়ন্ত্রণের জন্য সাপ্তাহিক খাবার পরিকল্পনা',
    descriptionEn: 'Step-by-step guide to plan weekly meals within your budget.',
    descriptionBn: 'সপ্তাহিক খাবার পরিকল্পনা করার ধাপ-দর-ধাপ গাইড।',
    contentEn: 'List what you have, plan meals around those items, then buy only what you need. This prevents waste and saves money.',
    contentBn: 'আপনার কাছে যা আছে তা তালিকা করুন, সেই অনুযায়ী খাবার পরিকল্পনা করুন, তারপর প্রয়োজনীয় জিনিসই কিনুন।',
    category: 'meal-planning',
    type: 'infographic',
    targetAudience: 'household',
  },
  {
    id: 'composting_setup',
    titleEn: 'Setting Up a Home Compost Bin',
    titleBn: 'ঘরে সার তৈরির বিন সেটআপ করা',
    descriptionEn: 'A beginner\'s guide to setting up and maintaining a home compost system.',
    descriptionBn: 'ঘরে সার তৈরির ব্যবস্থা সেটআপ এবং রক্ষণাবেক্ষণ করার গাইড।',
    contentEn: 'You need a container, brown materials (dry leaves), green materials (vegetable waste), and moisture. Maintain a 3:1 ratio of brown to green.',
    contentBn: 'একটি পাত্র, বাদামী উপকরণ (শুষ্ক পাতা), সবুজ উপকরণ (সবজির বর্জ্য), এবং আর্দ্রতা প্রয়োজন।',
    category: 'composting',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'batch_cooking',
    titleEn: 'Batch Cooking: Save Time and Money',
    titleBn: 'ব্যাচ রান্না: সময় এবং অর্থ বাঁচান',
    descriptionEn: 'Prepare multiple meals at once to reduce daily cooking time and food waste.',
    descriptionBn: 'একবারে একাধিক খাবার প্রস্তুত করুন এবং রান্নার সময় কমান।',
    contentEn: 'Prepare rice, dal, and vegetables in bulk. Store in containers for 3-4 days. This prevents daily cooking and reduces waste.',
    contentBn: 'চাউল, ডাল এবং সবজি বাল্কে প্রস্তুত করুন। পাত্রে 3-4 দিন সংরক্ষণ করুন।',
    category: 'meal-planning',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'organic_farming',
    titleEn: 'Starting Organic Farming on Small Land',
    titleBn: 'ছোট জমিতে জৈব চাষ শুরু করা',
    descriptionEn: 'Learn organic farming techniques suitable for small farms and household gardens.',
    descriptionBn: 'ছোট খামার এবং পরিবারের বাগানের জন্য জৈব চাষ কৌশল।',
    contentEn: 'Use compost instead of chemical fertilizers. Rotate crops yearly. Plant companion crops to prevent pests naturally.',
    contentBn: 'রাসায়নিক সার ব্যবহার করবেন না, সার ব্যবহার করুন। প্রতি বছর ফসল ঘোরান। প্রকৃতিগতভাবে কীটপতঙ্গ প্রতিরোধ করতে সঙ্গী ফসল রোপণ করুন।',
    category: 'waste-reduction',
    type: 'article',
    targetAudience: 'farmer',
  },
  {
    id: 'farmer_connect',
    titleEn: 'Connecting with Local Farmers for Fresh Produce',
    titleBn: 'স্থানীয় কৃষকদের সাথে সংযোগ করে তাজা পণ্য পান',
    descriptionEn: 'How to find and buy directly from local farmers in your area.',
    descriptionBn: 'আপনার এলাকার স্থানীয় কৃষকদের কাছ থেকে সরাসরি কিনুন।',
    contentEn: 'Local farming groups often organize weekly markets. Buy directly to support farmers, get fresh produce, and reduce transportation impact.',
    contentBn: 'স্থানীয় কৃষক গোষ্ঠী সাপ্তাহিক বাজার সংগঠিত করে। সরাসরি কিনুন কৃষকদের সমর্থন করতে এবং তাজা পণ্য পেতে।',
    category: 'budget-tips',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'water_conservation',
    titleEn: 'Water Conservation Tips for the Kitchen',
    titleBn: 'রসুইতে পানির ব্যবহার কমান',
    descriptionEn: 'Simple ways to conserve water while cooking and cleaning.',
    descriptionBn: 'রান্না এবং পরিষ্কার করার সময় পানি সাশ্রয় করুন।',
    contentEn: 'Reuse vegetable washing water for plants. Fill sink for washing instead of running water. Collect rainwater for kitchen use.',
    contentBn: 'সবজি ধোয়ার পানি গাছের জন্য ব্যবহার করুন। চলমান পানির পরিবর্তে সিঙ্ক পূরণ করুন। বৃষ্টির পানি সংগ্রহ করুন।',
    category: 'waste-reduction',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'pesticide_free',
    titleEn: 'Growing Pesticide-Free Vegetables at Home',
    titleBn: 'ঘরে কীটনাশকমুক্ত সবজি চাষ করুন',
    descriptionEn: 'Natural methods to grow healthy vegetables without harmful chemicals.',
    descriptionBn: 'ক্ষতিকর রাসায়নিক ছাড়াই সুস্থ সবজি চাষের প্রাকৃতিক পদ্ধতি।',
    contentEn: 'Use neem oil, cow urine, and companion planting. Remove pests by hand. Improve soil health with compost.',
    contentBn: 'নিম তেল, গরুর প্রস্রাব এবং সঙ্গী রোপণ ব্যবহার করুন। হাতে কীটপতঙ্গ অপসারণ করুন। সার দিয়ে মাটির স্বাস্থ্য উন্নত করুন।',
    category: 'waste-reduction',
    type: 'article',
    targetAudience: 'farmer',
  },
  {
    id: 'rice_storage',
    titleEn: 'Proper Rice Storage for Long-Term Use',
    titleBn: 'দীর্ঘমেয়াদী ব্যবহারের জন্য সঠিক চাউল সংরক্ষণ',
    descriptionEn: 'Learn how to store rice to prevent spoilage and pest infestation.',
    descriptionBn: 'চাউল নষ্ট হওয়া এবং কীটপতঙ্গ প্রতিরোধ করতে সংরক্ষণ করুন।',
    contentEn: 'Store in airtight containers with bay leaves. Keep in cool, dry place. Check monthly for insects.',
    contentBn: 'বে পাতা দিয়ে বায়ুরোধী পাত্রে রাখুন। ঠান্ডা শুষ্ক স্থানে রাখুন। মাসিক কীটপতঙ্গ পরীক্ষা করুন।',
    category: 'storage',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'dairy_care',
    titleEn: 'Proper Dairy Storage and Food Safety',
    titleBn: 'সঠিক দুগ্ধজাত পণ্য সংরক্ষণ এবং খাদ্য নিরাপত্তা',
    descriptionEn: 'Guidelines for storing dairy products safely to prevent spoilage.',
    descriptionBn: 'নষ্টতা প্রতিরোধ করতে দুগ্ধজাত পণ্য নিরাপদে সংরক্ষণ করুন।',
    contentEn: 'Keep milk at coldest part of fridge. Do not store on door. Check expiry dates. Use immediately after opening.',
    contentBn: 'দুধ রেফ্রিজারেটরের ঠান্ডা অংশে রাখুন। দরজায় রাখবেন না। মেয়াদ উত্তীর্ণ তারিখ পরীক্ষা করুন। খোলার পর অবিলম্বে ব্যবহার করুন।',
    category: 'storage',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'herbs_growing',
    titleEn: 'Growing Herbs in Your Kitchen Garden',
    titleBn: 'রসুইতের বাগানে ভেষজ চাষ করুন',
    descriptionEn: 'Easy-to-grow herbs for cooking that save money and reduce packaging waste.',
    descriptionBn: 'রান্নার জন্য সহজে চাষযোগ্য ভেষজ যা টাকা এবং প্যাকেজিং বর্জ্য কমায়।',
    contentEn: 'Grow cilantro, mint, parsley in small pots. Harvest regularly. Fresh herbs improve taste and health.',
    contentBn: 'ছোট পাত্রে ধনিয়া, পুদিনা, পার্সলে চাষ করুন। নিয়মিত ফসল কাটুন। তাজা ভেষজ স্বাদ এবং স্বাস্থ্য উন্নত করে।',
    category: 'meal-planning',
    type: 'article',
    targetAudience: 'household',
  },
  {
    id: 'zero_waste_kitchen',
    titleEn: 'Zero Waste Kitchen Tips',
    titleBn: 'শূন্য বর্জ্য রসুই টিপস',
    descriptionEn: 'Practical steps to minimize waste in your daily cooking routine.',
    descriptionBn: 'দৈনন্দিন রান্নায় বর্জ্য কমানোর ব্যবহারিক পদক্ষেপ।',
    contentEn: 'Use vegetable scraps for stock. Compost peels. Use glass containers instead of plastic. Buy in bulk.',
    contentBn: 'সবজির অবশেষ স্টক তৈরিতে ব্যবহার করুন। খোসা সার তৈরি করুন। প্লাস্টিকের পরিবর্তে কাচের পাত্র ব্যবহার করুন। বাল্কে কিনুন।',
    category: 'waste-reduction',
    type: 'infographic',
    targetAudience: 'household',
  },
];
